name : Publish Images

on:
  push:
    tags:
      - "*"

jobs:
  push:
    name : Build and push PushProx images 
    runs-on : ubuntu-latest
    steps:
      - name : Checkout repository
        uses: actions/checkout@v4
      - name : Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name : Build, test & validate
        run : make ci
        # setup tag name
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo $GITHUB_REF | sed -e "s|refs/tags/||") >> $GITHUB_ENV
      - name: Build and push PushProx client image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.proxy
          push: true
          tags: docker.io/rancher/pushprox-client:${{ env.TAG_NAME }}-client
          platforms: linux/amd64,linux/arm64
      - name: Build and push PushProx proxy image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.client
          push: true
          tags: docker.io/rancher/pushprox-proxy:${{ env.TAG_NAME }}-proxy
          platforms : linux/amd64,linux/arm64
